'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { store } from './Redux/Store';
import { Provider } from 'react-redux';

const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Health-Care-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <head> 
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
            integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>
  );
}
